# -------------------
# SoaromaCM
# Version 0.0.17
# -------------------
# To switch back to default chat, the command would be /ch global
# This takes the variable from defaultGlobal and that would be the "global" channel
# You can change that in any way you want too
# Anyone with the channel permission will be able to recieve messages as well as send messages to that specific channel
# -------------------
# To create another channel the format would be 
# channels:
#  name:
#    defaultGlobal: global
#    channelUponJoining: global
#    defaultGlobalPermission: ch.defaultGlobal.use
#    enableGlobalMessageFormat: true
#    defaultGlobalMessageFormat: '&8[&2Global&8]&f {player} &8--> &f{message}'
#    testChannel:
#      permission: ch.use.testChannel
#      prefix: '&8[&4testChannel&8]'
#      sendRegardlessOfCurrentChannel: true
#      enableDistanceMessage: false
#      distanceMessage: 25
#      messageFormat: "{channel-prefix} {player} &8--> &3{message}"
#      chlistDisplayAll: true
#      channelExists: true
#    anotherChannel:
#      permission: ch.use.anotherChannel
#      prefix: '&8[&4anotherChannel&8]'
#      sendRegardlessOfCurrentChannel: true
#      enableDistanceMessage: false
#      distanceMessage: 25
#      messageFormat: "{channel-prefix} {player} &8--> &3{message}"
#      chlistDisplayAll: true
#      channelExists: true
#    ThirdChannel:
#      permission: ch.use.ThirdChannel
#      prefix: '&8[&4anThirdChannel&8]'
#      sendRegardlessOfCurrentChannel: true
#      enableDistanceMessage: false
#      distanceMessage: 25
#      messageFormat: "{channel-prefix} {player} &8--> &3{message}"
#      chlistDisplayAll: true
#      channelExists: true
# -------------------
# channelUponJoining is the channel a player is put into upon joining
# -------------------
# enableGlobalMessageFormat meaning if true, then enable the formatting for 'global'/default chat
# defaultGlobalMessageFormat is the message format for regular chat
# -------------------
# enableDistanceMessage means if TRUE then send the message to the player within the channel in X amount of blocks
# distanceMessage is the amount of blocks
# -------------------
# chlistDisplayAll - if TRUE, then anyone doing /chlist will be able to see the channel, if FALSE then only people who has permission for that channel can
# see that the specific channel exists when doing /chlist
# channelExists - if the channel exists or not
# -------------------
# To switch to that specific channel, the command would be /ch (channel name), for example /ch testChannel
# To switch back to normal chat, type /ch global
# The permission to switch back to normal chat would be defaultGlobalPermission
# -------------------
# The variable sendRegardlessOfCurrentChannel means that if two players has the same permission for the channel
# and one player is in the current channel while the other is not in the current channel
# if this variable is FALSE it will only send messages to players whose channel and permission is the same
# The only disclaimers is that a channel cannot be called "defaultGlobal", "defaultGlobalPermission" and it cannot end with ".permission" or ".prefix"
# or start with "channels.name." or anything that the config files path ends with
# As these names will mess up the system internally, everything else you may use, which is a lot... Happy Channeling!